# Generated by Django 3.2.7 on 2021-09-12 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('macros', '0003_product_nutritional_values_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_values_weight',
            field=models.CharField(choices=[('100g', '100g'), ('100ml', '100ml'), ('serving', 'serving')], default='100g', max_length=10),
        ),
    ]
