# Generated by Django 3.2.7 on 2021-09-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210907_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='default.png', upload_to='background_images'),
        ),
    ]
