# Generated by Django 3.2.7 on 2021-09-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20210912_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
