# Generated by Django 3.2.7 on 2021-09-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_exercise_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='exercises',
            field=models.ManyToManyField(to='workout.Exercise'),
        ),
    ]
