# Generated by Django 3.2.7 on 2021-09-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_alter_template_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='user',
            new_name='author',
        ),
    ]
